name: delete

on:
  delete:

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name == 'ok'
    steps:
      - name: debug github context
        run: |
          env
          echo ${{github.event.ref_type}}
          echo ${{github.event.ref}}
