name: release

on:
  workflow_call:
    inputs:
      reference:
        type: string
        description: "Git reference to deploy (ex: vX.Y.Z, main)"
        required: true

  workflow_dispatch:
    inputs:
      reference:
        type: string
        description: "Git reference to deploy (ex: vX.Y.Z, main)"
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug github context
        run: |
          env
          git rev-parse HEAD
          TAG=$(git name-rev --tags --name-only $(git rev-parse HEAD))
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "tag: $TAG"
          echo "BRANCH_NAME: $BRANCH_NAME"
          

